- rel 3
Changed files:
    kernelrelease.patch -> 1.6
    xtables-addons.spec -> 1.83

diff --git a/kernelrelease.patch b/kernelrelease.patch
--- a/kernelrelease.patch
+++ b/kernelrelease.patch
@@ -1,10 +1,10 @@
-diff -ur xtables-addons-1.30/configure.ac xtables-addons-1.30.new//configure.ac
---- xtables-addons-1.30/configure.ac	2010-10-02 00:41:47.000000000 +0200
-+++ xtables-addons-1.30.new//configure.ac	2010-10-15 16:59:31.936357030 +0200
-@@ -38,38 +38,6 @@
+--- xtables-addons-1.31/configure.ac~	2010-12-02 22:13:08.366366978 +0100
++++ xtables-addons-1.31/configure.ac	2010-12-02 22:14:14.780561896 +0100
+@@ -39,47 +39,6 @@
+ 	-Winline -pipe -DXTABLES_LIBDIR=\\\"\${xtlibdir}\\\" \
  	-I\${XA_TOPSRCDIR}/include";
  
- #
+-#
 -# check kernel version
 -#
 -if grep -q "CentOS release 5\." /etc/redhat-release 2>/dev/null ||
@@ -13,6 +13,7 @@ diff -ur xtables-addons-1.30/configure.ac xtables-addons-1.30.new//configure.ac
 -	# Well, just a warning. Maybe the admin updated the kernel.
 -	echo "WARNING: This distribution's shipped kernel is not supported.";
 -fi;
+-AC_MSG_CHECKING([kernel version that we will build against])
 -krel="$(make -sC ${kbuilddir} kernelrelease)";
 -krel="${krel%%-*}";
 -kmajor="${krel%%.*}";
@@ -21,23 +22,29 @@ diff -ur xtables-addons-1.30/configure.ac xtables-addons-1.30.new//configure.ac
 -krel="${krel#*.}";
 -kmicro="${krel%%.*}";
 -if test "$kmicro" = "$krel"; then
+-	kmicro="$(($kmicro+0))"; # Get rid of non numbers ("2.6.36+" -> "2.6.36")
 -	kstable=0;
 -else
+-	kmicro="$(($kmicro+0))";
 -	kstable="${krel#*.}";
--	if test -z "$kstable"; then
--		kstable=0;
+-	kstable="$(($kstable+0))";
+-fi;
+-if test -z "$kmajor" -o -z "$kminor" -o -z "$kmicro"; then
+-	echo "WARNING: Version detection did not succeed. Continue at own luck.";
+-else
+-	echo "$kmajor.$kminor.$kmicro.$kstable in $kbuilddir";
+-	if test "$kmajor" -gt 2 -o "$kminor" -gt 6 -o "$kmicro" -gt 36; then
+-		echo "WARNING: You are trying a newer kernel. Results may vary. :-)";
+-	elif test \( "$kmajor" -lt 2 -o \
+-	    \( "$kmajor" -eq 2 -a "$kminor" -lt 6 \) -o \
+-	    \( "$kmajor" -eq 2 -a "$kminor" -eq 0 -a "$kmicro" -lt 17 \) -o \
+-	    \( "$kmajor" -eq 2 -a "$kminor" -eq 6 -a "$kmicro" -eq 18 -a \
+-	    "$kstable" -lt 5 \) \); then
+-		echo "ERROR: That kernel version is not supported. Please see INSTALL for minimum configuration.";
+-		exit 1;
 -	fi;
 -fi;
--echo "Found kernel version $kmajor.$kminor.$kmicro.$kstable in $kbuilddir";
--if test "$kmajor" -gt 2 -o "$kminor" -gt 6 -o "$kmicro" -gt 36; then
--	echo "WARNING: You are trying a newer kernel. Results may vary. :-)";
--elif test \( "$kmajor" -lt 2 -o "$kminor" -lt 6 -o "$kmicro" -lt 17 \) -o \
--    \( "$kmajor" -eq 2 -a "$kminor" -eq 6 -a "$kmicro" -eq 18 -a \
--    "$kstable" -lt 5 \); then
--	echo "ERROR: That kernel version is not supported. Please see INSTALL for minimum configuration.";
--	exit 1;
--fi;
- 
+-
  AC_SUBST([regular_CFLAGS])
  AC_SUBST([kbuilddir])
-Tylko w xtables-addons-1.30.new/: configure.ac~
+ AC_SUBST([xtlibdir])
